import { FormEvent, useEffect, useMemo, useState } from "react";
import { Bell, CalendarDays, ChevronLeft, ChevronRight, CircleDollarSign, Download, History, Home, Menu, Plus, Receipt, Settings, Sparkles, Target, Trash2, Upload, Users, WalletCards, X } from "lucide-react";
import { budgetSummary, cents, closeBudget, euro } from "./domain";
import { AppState, loadState, saveState } from "./store";
type View="dashboard"|"budget"|"expenses"|"contributions"|"surplus"|"projects"|"history"|"settings";
const navigation:[View,string,typeof Home][]=[["dashboard","Tableau de bord",Home],["budget","Budget",WalletCards],["expenses","Dépenses",Receipt],["contributions","Contributions",Users],["surplus","Surplus",CircleDollarSign],["projects","Projets",Target],["history","Historique",History],["settings","Paramètres",Settings]];
const iso=()=>new Date().toISOString().slice(0,10);
export default function App(){
 const [state,setState]=useState<AppState>(loadState),[view,setView]=useState<View>("dashboard"),[modal,setModal]=useState<"expense"|"payment"|"project"|null>(null),[member,setMember]=useState<string|null>(null),[menu,setMenu]=useState(false);
 const summary=useMemo(()=>budgetSummary(state.budget,state.members),[state]); useEffect(()=>saveState(state),[state]); const update=(f:(s:AppState)=>AppState)=>setState(s=>f(s)); const go=(v:View)=>{setView(v);setMenu(false)};
 function expense(e:FormEvent<HTMLFormElement>){e.preventDefault();const d=new FormData(e.currentTarget),n=Number(String(d.get("amount")).replace(",","."));if(n<=0)return;update(s=>({...s,budget:{...s.budget,expenses:[...s.budget.expenses,{id:crypto.randomUUID(),lineId:String(d.get("line")),amountCents:cents(n),date:String(d.get("date")),description:String(d.get("description"))}]}}));setModal(null)}
 function payment(e:FormEvent<HTMLFormElement>){e.preventDefault();const d=new FormData(e.currentTarget),n=Number(String(d.get("amount")).replace(",","."));if(!member||n<=0)return;update(s=>({...s,budget:{...s.budget,payments:[...s.budget.payments,{id:crypto.randomUUID(),memberId:member,amountCents:cents(n),date:iso()}]}}));setModal(null)}
 function project(e:FormEvent<HTMLFormElement>){e.preventDefault();const d=new FormData(e.currentTarget),target=Number(d.get("target"));update(s=>({...s,projects:[...s.projects,{id:crypto.randomUUID(),name:String(d.get("name")),targetCents:target?cents(target):undefined,allocatedCents:0}]}));setModal(null)}
 function close(){if(!confirm(`Clôturer ${state.budget.label} et transférer ${euro(summary.transferableSurplusCents)} ?`))return;update(s=>{const b=closeBudget(s.budget,s.members),amount=b.closedSurplusCents??0;return{...s,budget:b,surplusCents:s.surplusCents+amount,surplusEntries:amount?[{id:crypto.randomUUID(),amountCents:amount,label:`Clôture ${b.label}`,date:b.label,type:"saving"},...s.surplusEntries]:s.surplusEntries}})}
 function exportData(){const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([JSON.stringify(state,null,2)],{type:"application/json"}));a.download="budg-backup.json";a.click();URL.revokeObjectURL(a.href)}
 function importData(e:React.ChangeEvent<HTMLInputElement>){const f=e.target.files?.[0];if(!f)return;const r=new FileReader();r.onload=()=>{try{setState(JSON.parse(String(r.result)))}catch{alert("Sauvegarde invalide")}};r.readAsText(f)}
 return <div className="app-shell"><aside className={menu?"open":""}><div className="logo"><img src="/assets/logo-mark.svg"/><b>BUDG</b><button className="close-menu" onClick={()=>setMenu(false)}><X/></button></div><nav>{navigation.map(([id,label,I])=><button key={id} className={view===id?"active":""} onClick={()=>go(id)}><I size={18}/>{label}</button>)}</nav><div className="month-pick"><ChevronLeft size={16}/><b>{state.budget.label}</b><ChevronRight size={16}/></div><div className="household"><span>JM</span><div><b>{state.householdName}</b><small>Foyer actif</small></div><ChevronRight size={15}/></div></aside>{menu&&<div className="scrim" onClick={()=>setMenu(false)}/>}<main><header><button className="menu-button" onClick={()=>setMenu(true)}><Menu/></button><div><h1>{view==="dashboard"?<>Bonjour Jean <span>👋</span></>:navigation.find(n=>n[0]===view)?.[1]}</h1><p>{view==="dashboard"?`Voici votre situation pour ${state.budget.label.toLowerCase()}.`:state.budget.label}</p></div><div className="header-icons"><button><Bell size={19}/></button><button onClick={()=>go("settings")}><Settings size={19}/></button></div></header>
 {view==="dashboard"&&<Dashboard s={state} summary={summary} go={go} pay={(id:string)=>{setMember(id);setModal("payment")}}/>}{view==="budget"&&<Budget s={state} summary={summary}/>} {view==="expenses"&&<Expenses s={state} add={()=>setModal("expense")} remove={id=>update(s=>({...s,budget:{...s.budget,expenses:s.budget.expenses.filter(e=>e.id!==id)}}))}/>} {view==="contributions"&&<Contributions s={state} summary={summary} pay={(id:string)=>{setMember(id);setModal("payment")}}/>}{view==="surplus"&&<Surplus s={state}/>} {view==="projects"&&<Projects s={state} add={()=>setModal("project")}/>} {view==="history"&&<HistoryView s={state}/>} {view==="settings"&&<SettingsView s={state} setState={setState} exportData={exportData} importData={importData}/>} {view==="dashboard"&&state.budget.status!=="CLOSED"&&<button className="close-month" onClick={close}>Clôturer le mois <ChevronRight size={17}/></button>}</main><MobileNav view={view} go={go} add={()=>setModal("expense")}/>
 {modal==="expense"&&<Modal title="Ajouter une dépense" close={()=>setModal(null)}><form onSubmit={expense}><Field label="Montant (€)" name="amount" placeholder="0,00"/><label>Catégorie<select name="line">{state.budget.lines.map(l=><option value={l.id} key={l.id}>{l.name}</option>)}</select></label><Field label="Description" name="description" placeholder="Ex. Courses Carrefour"/><Field label="Date" name="date" type="date" value={iso()}/><button className="primary full">Enregistrer</button></form></Modal>}{modal==="payment"&&<Modal title="Enregistrer un versement" close={()=>setModal(null)}><form onSubmit={payment}><Field label="Montant (€)" name="amount" placeholder="0,00"/><button className="primary full">Confirmer</button></form></Modal>}{modal==="project"&&<Modal title="Nouveau projet" close={()=>setModal(null)}><form onSubmit={project}><Field label="Nom" name="name" placeholder="Ex. Vacances"/><Field label="Objectif (€)" name="target" placeholder="2 000"/><button className="primary full">Créer le projet</button></form></Modal>}</div>}

function Dashboard({s,summary,go,pay}:any){return <><div className="dashboard-grid"><Panel title="Contributions" link={()=>go("contributions")}><div className="contrib-list">{s.members.map((m:any)=>{const left=Math.max(0,summary.expected[m.id]-summary.paid[m.id]);return <div className="person" key={m.id}><div className={`face ${m.id}`}>{m.name[0]}</div><div><b>{m.name}</b><small>{euro(summary.expected[m.id])} attendus</small></div><strong>{euro(summary.paid[m.id])}<small className={left?"warn":"ok"}>{left?`${euro(left)} à verser`:"À jour ✓"}</small></strong>{left>0&&<button onClick={()=>pay(m.id)}><Plus/></button>}</div>})}</div></Panel><Panel title="Budget du mois" link={()=>go("budget")}><Donut spent={summary.spentCents} planned={summary.plannedCents}/><b className="available">{euro(Math.max(0,summary.plannedCents-summary.spentCents))} disponibles</b></Panel><Panel title="Pot Surplus" link={()=>go("surplus")}><div className="surplus-hero"><div><strong>{euro(s.surplusCents)}</strong><span>disponibles</span><b>+170 € ce mois</b></div><img src="/assets/budg-plant.png"/></div></Panel></div><div className="lower-grid"><BudgetTable s={s}/><Recent s={s} go={go}/></div></>}
function Panel({title,children,link}:any){return <section className="panel"><h3>{title}</h3>{children}<button className="panel-link" onClick={link}>Voir le détail <ChevronRight size={14}/></button></section>}
function Donut({spent,planned}:{spent:number;planned:number}){const p=Math.min(100,spent/planned*100);return <div className="donut-wrap"><div><b>{euro(planned)}</b><small>prévu</small></div><div className="donut" style={{background:`conic-gradient(#2e7559 ${p}%,#dceadf 0)`}}><span><b>{euro(spent)}</b><small>dépensés</small></span></div></div>}
function BudgetTable({s}:{s:AppState}){return <section className="panel budget-list"><h3>Budget par catégorie</h3>{s.budget.lines.map(l=>{const n=s.budget.expenses.filter(e=>e.lineId===l.id).reduce((a,b)=>a+b.amountCents,0),p=Math.min(100,n/l.plannedCents*100);return <div className="budget-row" key={l.id}><b>{l.name}</b><span>{euro(l.plannedCents)}</span><div><i style={{width:`${p}%`}}/></div><small>{euro(n)} · {Math.round(n/l.plannedCents*100)}%</small></div>})}</section>}
function Recent({s,go}:{s:AppState;go:(v:View)=>void}){return <section className="panel recent"><h3>Dépenses récentes</h3>{[...s.budget.expenses].reverse().slice(0,5).map(e=><div key={e.id}><span><Receipt size={15}/></span><p><b>{e.description}</b><small>{new Date(e.date).toLocaleDateString("fr-FR",{day:"numeric",month:"short",year:"numeric"})}</small></p><strong>{euro(e.amountCents)}</strong></div>)}<button className="panel-link" onClick={()=>go("expenses")}>Voir toutes les dépenses <ChevronRight size={14}/></button></section>}
function Budget({s,summary}:{s:AppState;summary:any}){return <div className="page-grid"><section className="panel summary-card"><Donut spent={summary.spentCents} planned={summary.plannedCents}/><div className="metric"><span>Reste disponible</span><b>{euro(Math.max(0,summary.plannedCents-summary.spentCents))}</b></div></section><BudgetTable s={s}/></div>}
function Expenses({s,add,remove}:{s:AppState;add:()=>void;remove:(id:string)=>void}){return <section className="panel page-panel"><div className="section-head"><div><h2>Toutes les dépenses</h2><p>{s.budget.expenses.length} opérations ce mois</p></div><button className="primary" onClick={add}><Plus/>Ajouter</button></div><div className="transaction-list">{[...s.budget.expenses].reverse().map(e=><div key={e.id}><span className="transaction-icon"><Receipt/></span><p><b>{e.description}</b><small>{s.budget.lines.find(l=>l.id===e.lineId)?.name} · {new Date(e.date).toLocaleDateString("fr-FR")}</small></p><strong>{euro(e.amountCents)}</strong><button className="trash" onClick={()=>confirm("Supprimer cette dépense ?")&&remove(e.id)}><Trash2/></button></div>)}</div></section>}
function Contributions({s,summary,pay}:any){return <div className="cards-two">{s.members.map((m:any)=>{const left=Math.max(0,summary.expected[m.id]-summary.paid[m.id]);return <section className="panel member-detail" key={m.id}><div className={`face large ${m.id}`}>{m.name[0]}</div><h2>{m.name}</h2><div className="metric"><span>Contribution attendue</span><b>{euro(summary.expected[m.id])}</b></div><div className="metric"><span>Déjà versé</span><b className="green">{euro(summary.paid[m.id])}</b></div><div className="metric"><span>{left?"Reste à verser":"Statut"}</span><b className={left?"orange":"green"}>{left?euro(left):"À jour ✓"}</b></div><button className="secondary full" onClick={()=>pay(m.id)}>Ajouter un versement</button></section>})}</div>}
function Surplus({s}:{s:AppState}){return <div className="surplus-page"><section className="panel surplus-balance"><div><span>Solde actuel</span><strong>{euro(s.surplusCents)}</strong><small>argent commun disponible</small></div><img src="/assets/budg-plant.png"/></section><section className="panel page-panel"><h2>Historique</h2><div className="transaction-list">{s.surplusEntries.map(x=><div key={x.id}><span className="transaction-icon"><Sparkles/></span><p><b>{x.label}</b><small>{x.date}</small></p><strong className={x.amountCents>=0?"green":"orange"}>{x.amountCents>=0?"+":""}{euro(x.amountCents)}</strong></div>)}</div></section></div>}
function Projects({s,add}:{s:AppState;add:()=>void}){return <section className="panel page-panel"><div className="section-head"><div><h2>Projets communs</h2><p>Donnez un objectif à vos économies.</p></div><button className="primary" onClick={add}><Plus/>Nouveau projet</button></div><div className="project-grid">{s.projects.map(p=>{const ratio=p.targetCents?Math.min(100,p.allocatedCents/p.targetCents*100):0;return <article key={p.id}><div className="project-icon"><Target/></div><h3>{p.name}</h3><strong>{euro(p.allocatedCents)} <small>/ {euro(p.targetCents??0)}</small></strong><div className="bar"><i style={{width:`${ratio}%`}}/></div><p>{Math.round(ratio)} % financé</p></article>})}</div></section>}
function HistoryView({s}:{s:AppState}){return <section className="panel page-panel"><h2>Mois précédents</h2><div className="history-card"><CalendarDays/><div><b>Juillet 2026</b><span>Budget clôturé</span></div><strong>+65,00 €</strong><ChevronRight/></div><div className="history-card current"><CalendarDays/><div><b>{s.budget.label}</b><span>{s.budget.status==="CLOSED"?"Budget clôturé":"Budget en cours"}</span></div><strong>{euro(s.budget.closedSurplusCents??0)}</strong><ChevronRight/></div></section>}
function SettingsView({s,setState,exportData,importData}:any){return <div className="settings-grid"><section className="panel page-panel"><h2>Foyer et revenus</h2>{s.members.map((m:any)=><div className="setting-row" key={m.id}><div className={`face ${m.id}`}>{m.name[0]}</div><div><b>{m.name}</b><small>Revenu net mensuel</small></div><strong>{euro(m.incomeCents)}</strong></div>)}</section><section className="panel page-panel"><h2>Données locales</h2><p className="muted">Exportez une sauvegarde complète ou restaurez vos données. Rien ne quitte cet appareil.</p><button className="secondary full" onClick={exportData}><Download/>Exporter une sauvegarde</button><label className="secondary full upload"><Upload/>Restaurer une sauvegarde<input type="file" accept="application/json" onChange={importData}/></label><button className="danger-button" onClick={()=>confirm("Réinitialiser toutes les données locales ?")&&setState(loadState())}>Réinitialiser l’application</button></section></div>}
function MobileNav({view,go,add}:any){return <nav className="mobile-nav">{(["dashboard","budget","add","surplus","settings"] as const).map(id=>id==="add"?<button className="mobile-add" key={id} onClick={add}><Plus/><span>Ajouter</span></button>:(()=>{const n=navigation.find(x=>x[0]===id)!;const I=n[2];return <button key={id} className={view===id?"active":""} onClick={()=>go(id)}><I/><span>{id==="dashboard"?"Accueil":n[1]}</span></button>})())}</nav>}
function Modal({title,close,children}:any){return <div className="overlay" onMouseDown={close}><div className="modal" onMouseDown={e=>e.stopPropagation()}><div className="modal-head"><h2>{title}</h2><button onClick={close}><X/></button></div>{children}</div></div>}
function Field({label,name,placeholder,type="text",value}:any){return <label>{label}<input autoFocus={name==="amount"||name==="name"} name={name} placeholder={placeholder} type={type} defaultValue={value} required/></label>}
